// Generated by gencpp from file ogretici_paket/drone.msg
// DO NOT EDIT!


#ifndef OGRETICI_PAKET_MESSAGE_DRONE_H
#define OGRETICI_PAKET_MESSAGE_DRONE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ogretici_paket
{
template <class ContainerAllocator>
struct drone_
{
  typedef drone_<ContainerAllocator> Type;

  drone_()
    : hiz(0)
    , isim()
    , batarya(0)  {
    }
  drone_(const ContainerAllocator& _alloc)
    : hiz(0)
    , isim(_alloc)
    , batarya(0)  {
  (void)_alloc;
    }



   typedef int32_t _hiz_type;
  _hiz_type hiz;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _isim_type;
  _isim_type isim;

   typedef int32_t _batarya_type;
  _batarya_type batarya;





  typedef boost::shared_ptr< ::ogretici_paket::drone_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ogretici_paket::drone_<ContainerAllocator> const> ConstPtr;

}; // struct drone_

typedef ::ogretici_paket::drone_<std::allocator<void> > drone;

typedef boost::shared_ptr< ::ogretici_paket::drone > dronePtr;
typedef boost::shared_ptr< ::ogretici_paket::drone const> droneConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ogretici_paket::drone_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ogretici_paket::drone_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ogretici_paket::drone_<ContainerAllocator1> & lhs, const ::ogretici_paket::drone_<ContainerAllocator2> & rhs)
{
  return lhs.hiz == rhs.hiz &&
    lhs.isim == rhs.isim &&
    lhs.batarya == rhs.batarya;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ogretici_paket::drone_<ContainerAllocator1> & lhs, const ::ogretici_paket::drone_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ogretici_paket

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ogretici_paket::drone_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ogretici_paket::drone_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ogretici_paket::drone_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ogretici_paket::drone_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ogretici_paket::drone_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ogretici_paket::drone_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ogretici_paket::drone_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ab3da279a675c6dfa18bb8afc332a0ab";
  }

  static const char* value(const ::ogretici_paket::drone_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xab3da279a675c6dfULL;
  static const uint64_t static_value2 = 0xa18bb8afc332a0abULL;
};

template<class ContainerAllocator>
struct DataType< ::ogretici_paket::drone_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ogretici_paket/drone";
  }

  static const char* value(const ::ogretici_paket::drone_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ogretici_paket::drone_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 hiz\n"
"string isim\n"
"int32 batarya\n"
;
  }

  static const char* value(const ::ogretici_paket::drone_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ogretici_paket::drone_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hiz);
      stream.next(m.isim);
      stream.next(m.batarya);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct drone_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ogretici_paket::drone_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ogretici_paket::drone_<ContainerAllocator>& v)
  {
    s << indent << "hiz: ";
    Printer<int32_t>::stream(s, indent + "  ", v.hiz);
    s << indent << "isim: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.isim);
    s << indent << "batarya: ";
    Printer<int32_t>::stream(s, indent + "  ", v.batarya);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OGRETICI_PAKET_MESSAGE_DRONE_H
