// Generated by gencpp from file basit_uygulamalar/CemberHaraket.msg
// DO NOT EDIT!


#ifndef BASIT_UYGULAMALAR_MESSAGE_CEMBERHARAKET_H
#define BASIT_UYGULAMALAR_MESSAGE_CEMBERHARAKET_H

#include <ros/service_traits.h>


#include <basit_uygulamalar/CemberHaraketRequest.h>
#include <basit_uygulamalar/CemberHaraketResponse.h>


namespace basit_uygulamalar
{

struct CemberHaraket
{

typedef CemberHaraketRequest Request;
typedef CemberHaraketResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CemberHaraket
} // namespace basit_uygulamalar


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::basit_uygulamalar::CemberHaraket > {
  static const char* value()
  {
    return "534fdc954659adaf837ecd56d547676d";
  }

  static const char* value(const ::basit_uygulamalar::CemberHaraket&) { return value(); }
};

template<>
struct DataType< ::basit_uygulamalar::CemberHaraket > {
  static const char* value()
  {
    return "basit_uygulamalar/CemberHaraket";
  }

  static const char* value(const ::basit_uygulamalar::CemberHaraket&) { return value(); }
};


// service_traits::MD5Sum< ::basit_uygulamalar::CemberHaraketRequest> should match
// service_traits::MD5Sum< ::basit_uygulamalar::CemberHaraket >
template<>
struct MD5Sum< ::basit_uygulamalar::CemberHaraketRequest>
{
  static const char* value()
  {
    return MD5Sum< ::basit_uygulamalar::CemberHaraket >::value();
  }
  static const char* value(const ::basit_uygulamalar::CemberHaraketRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::basit_uygulamalar::CemberHaraketRequest> should match
// service_traits::DataType< ::basit_uygulamalar::CemberHaraket >
template<>
struct DataType< ::basit_uygulamalar::CemberHaraketRequest>
{
  static const char* value()
  {
    return DataType< ::basit_uygulamalar::CemberHaraket >::value();
  }
  static const char* value(const ::basit_uygulamalar::CemberHaraketRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::basit_uygulamalar::CemberHaraketResponse> should match
// service_traits::MD5Sum< ::basit_uygulamalar::CemberHaraket >
template<>
struct MD5Sum< ::basit_uygulamalar::CemberHaraketResponse>
{
  static const char* value()
  {
    return MD5Sum< ::basit_uygulamalar::CemberHaraket >::value();
  }
  static const char* value(const ::basit_uygulamalar::CemberHaraketResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::basit_uygulamalar::CemberHaraketResponse> should match
// service_traits::DataType< ::basit_uygulamalar::CemberHaraket >
template<>
struct DataType< ::basit_uygulamalar::CemberHaraketResponse>
{
  static const char* value()
  {
    return DataType< ::basit_uygulamalar::CemberHaraket >::value();
  }
  static const char* value(const ::basit_uygulamalar::CemberHaraketResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BASIT_UYGULAMALAR_MESSAGE_CEMBERHARAKET_H
